### ISSUE TITLE
Duplicate agents in properties table

### ISSUE THREAD

**Issue by dhamaris** [paperswithcode/sota-extractor#18]
Hello,

I am not sure of whether this is a bug or a feature:
https://paperswithcode.com/sota/visual-question-answering-on-gqa-test2019

![image](https://user-images.githubusercontent.com/1392485/124633495-9d89c300-de85-11eb-9fe8-9d9fda8c4da2.png)

Is it ok that agent is repeated? I was assuming that I would only have 1 agent if all other fields (paperUrl, date, source, etc) are the same.

Thank you

**Comment by dhamaris** [comment]
[redundant_tuplas_by_metric_pwc.xlsx](https://github.com/paperswithcode/sota-extractor/files/6772180/redundant_tuplas_by_metric_pwc.xlsx)
I don't know if this will be of any use, but I identified the tuplas of experiments that contain more than one value when grouping by task, dataset, agent, paperDate, paperUrl and metric.

**Comment by omarsar** [comment]
@dhamaris Thanks for opening this issue. Looking at the original source of where the result came, it appears that the submissions are unique in the sense that they come from two different authors.

**Comment by omarsar** [comment]
I am not sure how to fix what you are trying to achieve. Not sure about it, but I am inclined to think that the results correspond two different experiments by two different users. Maybe they use similar model, backbone, experimental setup, or even same code base, as it is common in public community leaderboards such as Kaggle. If the results are obtained from external leaderboards like in this case, it is possible we will see this type of results. If the results are added on our website directly, it is less common as results are added directly through papers, helping to preserve one model to one result relationship.
