### ISSUE TITLE
How do you add a link for a reproducible example of a model?

### ISSUE THREAD

**Issue by dynamicwebpaige** [paperswithcode/sota-extractor#20]
Am not sure when this feature was introduced, but I *love* that Colab notebooks for models on Papers with Code are automatically referenced immediately below their repos ([example](https://paperswithcode.com/paper/slicing-aided-hyper-inference-and-fine-tuning)):

<img width="528" alt="Screen Shot 2022-02-23 at 10 25 34 AM" src="https://user-images.githubusercontent.com/3712347/155383402-4beba839-8f82-460a-ae0a-695db440feb6.png">

Am assuming that there is some sort of logic in the website that looks for `colab.research.google.com` links in models' `README`s? What would a user need to do to add a similar link for a demo of a model in HuggingFace's Spaces, or in a reproducible [Codespaces](https://github.com/features/codespaces) or [Replicate.ai](https://replicate.com/) instance?

Thank you!

cc: @alefnula @gcucurull @rstojnic

**Comment by rstojnic** [comment]
Hi @dynamicwebpaige - Yes that's correct, we get the Colab links from the repo README and in principle we could also parse out links to HF Spaces, Codespaces and Replicate.ai. We would leave it up to the repo maintainer to choose which one they want to link to.

**Comment by rstojnic** [comment]
This has now been added - you can see example on these papers: https://paperswithcode.com/paper/slicing-aided-hyper-inference-and-fine-tuning and https://paperswithcode.com/paper/mask2former-for-video-instance-segmentation

**Comment by dynamicwebpaige** [comment]
This is so cool! Thank you for the add, @rstojnic. 😍

**Comment by bfirsh** [comment]
Thanks for the links @rstojnic! 😄

**Comment by bfirsh** [comment]
It doesn't seem to be working on StyleCLIP: https://paperswithcode.com/paper/styleclip-text-driven-manipulation-of

Maybe this is because they're using our old domain (replicate.ai) in the readme?

**Comment by satpalsr** [comment]
Hey @rstojnic , I plan to add some Hugging Face space demos links as shown in your examples. This is not for any particular repo but for many repositories of which I am not a maintainer. How can I go about doing that?
